const express = require('express')
const crypto = require('crypto')
const router = express.Router()
const { supabaseAdmin } = require('../lib/supabase_admin')

router.post('/', async (req, res, next) => {
  try {
    const { razorpay_payment_id, razorpay_order_id, razorpay_signature, userId, amount } = req.body

    if (!razorpay_payment_id || !razorpay_order_id || !razorpay_signature || !userId || !amount) {
      return res.status(400).json({ error: 'Missing required payment verification fields' })
    }

    const amountNum = Number(amount)
    if (isNaN(amountNum) || amountNum <= 0) {
      return res.status(400).json({ error: 'Invalid amount' })
    }

    // Verify HMAC-SHA256 signature generated by Razorpay
    const bodyToSign = razorpay_order_id + '|' + razorpay_payment_id
    const expectedSignature = crypto
      .createHmac('sha256', process.env.RAZORPAY_KEY_SECRET)
      .update(bodyToSign)
      .digest('hex')

    if (expectedSignature !== razorpay_signature) {
      console.error('[confirm-payment] Invalid Razorpay signature')
      return res.status(400).json({ error: 'Invalid payment signature' })
    }

    // Signature verified — credit user's Talon wallet via Supabase RPC
    const { error: creditError } = await supabaseAdmin.rpc('credit_wallet', {
      p_user_id: userId,
      p_amount: amountNum,
      p_category: 'topup',
      p_reference_id: razorpay_payment_id,
      p_description: `Wallet top-up — ₹${amountNum}`,
    })

    if (creditError) {
      console.error('[confirm-payment] credit_wallet failed:', creditError.message)
      return res.status(500).json({ error: creditError.message || 'Failed to credit wallet' })
    }

    console.log(`[confirm-payment] Successfully credited ${amountNum} Talons to user ${userId}`)
    return res.status(200).json({ success: true, message: 'Wallet credited successfully' })
  } catch (err) {
    next(err)
  }
})

module.exports = router
